---

- names: ['The NERD tree']
  authors: [Marty Grenfell]
  urls:
    - http://www.vim.org/scripts/script.php?script_id=1658
  repo: git://github.com/scrooloose/nerdtree.git
  description: 'A tree explorer plugin for navigating the filesystem'
  comment:
  plugin_type: plugin
  dir: nerdtree

- names: [ruby.vim]
  authors: [Tim Pope]
  urls:
    - http://vim-ruby.rubyforge.org/
  repo: git://github.com/vim-ruby/vim-ruby.git
  description: 'Ruby on Rails: easy file navigation, enhanced syntax highlighting, and more'
  plugin_type: plugin
  dir: ruby

- names: [rails.vim]
  authors: [Tim Pope]
  urls:
    - http://www.vim.org/scripts/script.php?script_id=1567
  repo: git://github.com/tpope/vim-rails.git
  description: 'Ruby on Rails: easy file navigation, enhanced syntax highlighting, and more'
  comment:
  plugin_type: plugin
  dir: rails

- names: [surround.vim]
  authors: [Tim Pope]
  urls:
    - http://www.vim.org/scripts/script.php?script_id=1697
  repo: git://github.com/tpope/vim-surround.git
  description: 'Delete/change/add parentheses/quotes/XML-tags/much more with ease'
  comment:
  plugin_type: plugin
  dir: surround

- names: [ragtag.vim]
  authors: [Tim Pope]
  urls:
    - http://www.vim.org/scripts/script.php?script_id=1896
  repo: git://github.com/tpope/vim-ragtag.git
  description: 'A set of mappings for HTML, XML, PHP, ASP, eRuby, JSP, and more (formerly allml)'
  comment:
  plugin_type: plugin
  dir: ragtag

- names: [ack.vim]
  authors: [Miles Sterrett]
  urls:
    - http://www.vim.org/scripts/script.php?script_id=2572
  repo: git://github.com/mileszs/ack.vim.git
  description: "Plugin for the Perl module / CLI script 'ack'"
  comment:
  plugin_type: plugin
  #vim_org_id: 10433
  #file_type: tar.gz
  dir: ack

- names: [Align]
  authors: [Charles Campbell]
  urls:
    - http://www.vim.org/scripts/script.php?script_id=294
  repo: git://github.com/tsaleh/vim-align.git
  description: 'Align: Help folks to align text, eqns, declarations, tables, etc'
  comment: 'Look this examples: http://mysite.verizon.net/astronaut/vim/align.html#Examples'
  plugin_type: plugin
  dir: align

- names: [gardener]
  authors: [Maestro Entheon, Hariton Mizgir]
  urls:
    - http://www.vim.org/scripts/script.php?script_id=294
  repo: git://github.com/hariton/gardener.git
  description: 'Dark and colorful forrest khaki theme works with 256 color xterms'
  comment:
  plugin_type: colors
  dir: gardener

- names: [fugitive.vim]
  authors: [Tim Pope]
  urls:
    - http://github.com/tpope/vim-fugitive
    - http://www.vim.org/scripts/script.php?script_id=2975
  repo: git://github.com/tpope/vim-fugitive.git
  description: 'Git wrapper'
  comment: 'This plugin depends onvim-git'
  plugin_type: plugin
  dir: fugitive

- names: [vim-git]
  authors: [Tim Pope]
  urls:
    - http://github.com/tpope/vim-git
    - http://www.vim.org/scripts/script.php?script_id=1654
  repo: git://github.com/tpope/vim-git.git
  description: 'Git runtime files'
  comment:
  plugin_type: plugin
  dir: git

- names: [FuzzyFinder, fuf]
  authors: [Takeshi Nishida]
  urls:
    - http://www.vim.org/scripts/script.php?script_id=1984
  description: 'buffer/file/command/tag/etc explorer with fuzzy matching'
  comment:
  plugin_type: plugin
  vim_org_id: 11852 # 3.5, 2009-12-03, 7.0
  file_type: zip
  dir: fuzzy_finder

- names: [matchit]
  authors: [Benji Fisher]
  urls:
    - http://www.vim.org/scripts/script.php?script_id=39
  description: 'extended % matching for HTML, LaTeX, and many other languages'
  comment:
  plugin_type: plugin
  vim_org_id: 8196
  file_type: zip
  dir: matchit


- names: [Marks Browser]
  authors: [Viktor Kojouharov]
  urls:
    - http://www.vim.org/scripts/script.php?script_id=1706
  description:
  comment:
  plugin_type: plugin
  vim_org_id: 6408 # 0.9, 2006-11-13, 7.0
  file_type: vim
  dir: marksbrowser

- names: [IndexedSearch]
  authors: [Yakov Lerner]
  urls:
    - http://www.vim.org/scripts/script.php?script_id=1682
  description: "shows  'Nth match out of M'  at every search (index of match+total # matches)"
  comment:
  plugin_type: plugin
  vim_org_id: 7062 # 070503, 2007-05-03, 6.0
  file_type: vim
  dir: indexed_search

- names: [Scratch]
  authors: [Yegappan Lakshmanan]
  urls:
    - http://www.vim.org/scripts/script.php?script_id=664
  plugin_type: plugin
  vim_org_id: 2050 # 1.0, 2003-06-08, 6.0
  file_type: vim
  dir: scratch

- names: [taglist.vim]
  authors: [Yegappan Lakshmanan]
  urls:
    - http://www.vim.org/scripts/script.php?script_id=273
  description: 'Source code browser (supports C/C++, java, perl, python, tcl, sql, etc)'
  plugin_type: plugin
  vim_org_id: 7701 # 4.5, 2007-09-21, 6.0
  file_type: zip
  dir: taglist



- names: [jQuery]
  authors: [Bruno Michel]
  urls:
    - http://www.vim.org/scripts/script.php?script_id=2416
  description: 'some colorations for jQuery keywords and for CSS selectors'
  comment:
  plugin_type: syntax
  vim_org_id: 12107 # 0.4, 2010-02-02, 6.0
  file_type: vim
  dir: jquery

- names: [gist]
  authors: [Yasuhiro Matsumoto]
  urls:
    - http://www.vim.org/scripts/script.php?script_id=2423
  plugin_type: plugin
  vim_org_id: 12732 # 3.5, 2010-03-29, 7.0
  file_type: vim
  dir: gist

- names: [YankRing]
  authors: [David Fishburn]
  urls:
    - http://www.vim.org/scripts/script.php?script_id=1234
  description: 'Maintains a history of previous yanks, changes and deletes'
  comment:
  plugin_type: plugin
  vim_org_id: 12258
  file_type: zip
  dir: yankring


- names: [vim-indent-object]
  authors: [Michael Smith]
  urls:
    - http://www.vim.org/scripts/script.php?script_id=3037
  description: 'This plugin defines a new text object, based on indentation levels.'
  comment:
  plugin_type: plugin
  repo: git://github.com/michaeljsmith/vim-indent-object.git
  dir: vim-indent-object


- names: [cocoa.vim]
  authors: [Michael Sanders]
  urls:
    - http://www.vim.org/scripts/script.php?script_id=2674
  description: 'Cocoa.vim is a collection of scripts designed to make it easier to develop Cocoa/Objective-C applications'
  comment:
  plugin_type: plugin
  repo: git://github.com/msanders/cocoa.vim.git
  dir: cocoa-dot-vim

- names: [autocorrect.vim]
  authors: [Anthony Panozzo]
  urls:
    - http://www.vim.org/scripts/script.php?script_id=2429
  description: 'correcting typos and misspellings'
  comment:
  plugin_type: plugin
  repo: git://github.com/panozzaj/vim-autocorrect.git
  dir: autocorrect

- names: [histwin.vim]
  authors: [Christian Brabandt]
  urls:
    - http://www.vim.org/scripts/script.php?script_id=2932
  description: 'this plugin allows for easy navigation between the different undo-branches for a file'
  comment:
  plugin_type: plugin
  repo: git://github.com/chrisbra/histwin.vim.git
  dir: histwin


- names: [Conque Shell]
  authors: [Nico Raffo]
  urls:
    - http://www.vim.org/scripts/script.php?script_id=2771
  description: 'Run interactive commands inside a Vim buffer'
  comment:
  plugin_type: plugin
  svnrepo: http://conque.googlecode.com/svn/trunk/
  dir: conque

- names: [UltiSnips]
  authors: [Holger Rapp]
  urls:
    - http://www.vim.org/scripts/script.php?script_id=2715
  description: 'The ultimate snippet solution for python enabled Vim'
  comment:
  plugin_type: plugin
  bzrrepo: "lp:ultisnips"
  dir: ultisnips



- names: [operator-user]
  authors: [Kana Natsuno]
  urls:
    - http://www.vim.org/scripts/script.php?script_id=2692
  description: 'Define your own operator easily '
  comment:
  plugin_type: plugin
  repo: git://github.com/kana/vim-operator-user.git
  dir: operatoruser








- names: [Vimball]
  authors: [Charles Campbell]
  urls:
    - http://www.vim.org/scripts/script.php?script_id=1502
  description: 'vim-based archiver: builds, extracts, and previews'
  comment: this needs to appear before any vba plugins
  vim_org_id: 11981
  file_type: tar.gz
  dir: vimball

- names: [netrw]
  authors: [Charles Campbell]
  urls:
    - http://www.vim.org/scripts/script.php?script_id=1075
  description: 'Network oriented reading, writing, and browsing'
  comment:
  plugin_type: plugin
  vim_org_id: 11979
  file_type: vba.gz
  dir: netrw

- names: [camelcasemotion]
  authors: [Ingo Karkat]
  urls:
    - http://www.vim.org/scripts/script.php?script_id=1905
  description: 'Motion through CamelCaseWords and underscore_notation'
  comment:
  plugin_type: plugin
  vim_org_id: 10530
  file_type: vba.gz
  dir: camelcasemotion

- names: [operator-camelize]
  authors: [tyru]
  urls:
    - http://www.vim.org/scripts/script.php?script_id=3046
  description: 'snake_case -> SnakeCase, CamelCase -> camel_case'
  comment:
  plugin_type: plugin
  vim_org_id: 12793
  file_type: zip
  dir: operatorcamelize




- names: [SuperTab continued]
  authors: [Eric Van Dewoestine]
  urls:
    - http://www.vim.org/scripts/script.php?script_id=1643
  description: 'Do all your insert-mode completion with Tab'
  comment:
  vim_org_id: 11853
  file_type: vba
  dir: supertab




- names: [ZoomWin]
  authors: [Charles Campbell]
  urls:
    - http://www.vim.org/scripts/script.php?script_id=508
  description: 'Zoom in/out  of windows (toggle between one window and multi-window)'
  comment:
  plugin_type: plugin
  vim_org_id: 9865
  file_type: vba.gz
  dir: zoomwin



- names: [tlib]
  authors: [Tom Link]
  urls:
    - http://www.vim.org/scripts/script.php?script_id=1863
  description: 'Some utility functions '
  comment:
  plugin_type: plugin
  vim_org_id: 12751
  file_type: vba
  dir: tlib


- names: [bufkill.vim]
  authors: [John Orr]
  urls:
    - http://www.vim.org/scripts/script.php?script_id=1147
  description: 'Unload/delete/wipe a buffer, keep its window(s), display last accessed buffer(s) '
  comment:
  plugin_type: plugin
  vim_org_id: 3671
  file_type: vim
  dir: bufkill


- names: [CmdlineComplete]
  authors: [Yuheng Xie]
  urls:
    - http://www.vim.org/scripts/script.php?script_id=2222
  description: 'When editing the command-line (: / etc.), press Ctrl-P or Ctrl-N to complete the word before the cursor'
  comment:
  plugin_type: plugin
  vim_org_id: 8969
  file_type: vim
  dir: cmdline-complete



- names: [DoxygenToolkit]
  authors: [Mathias Lorente]
  urls:
    - http://www.vim.org/scripts/script.php?script_id=987
  description: 'Simplify Doxygen documentation in C, C++, Python'
  comment:
  plugin_type: plugin
  vim_org_id: 11878
  file_type: vim
  dir: doxygen-toolkit


- names: [pdc]
  authors: [jeremy schultz]
  urls:
    - http://www.vim.org/scripts/script.php?script_id=2389
  description: 'Syntax file for Pandoc'
  comment:
  plugin_type: syntax
  vim_org_id: 9430
  file_type: vim
  dir: pdc

- names: [repeat.vim]
  authors: [Tim Pope]
  urls:
    - http://www.vim.org/scripts/script.php?script_id=2136
  description: 'Use the repeat command (.) with supported plugins  '
  comment:
  plugin_type: plugin
  repo: git://github.com/tpope/vim-repeat.git
  dir: repeat


- names: [xmledit]
  authors: [Devin Weaver]
  urls:
    - http://www.vim.org/scripts/script.php?script_id=301
  description: ' A filetype plugin to help edit XML, HTML, and SGML documents '
  comment:
  plugin_type: plugin
  repo: git://github.com/sukima/xmledit.git
  dir: xmledit


- names: [candycode]
  authors: [Justin Constantino]
  urls:
    - http://www.vim.org/scripts/script.php?script_id=1635
  description: ' A colorful dark scheme with bright pastel colors  '
  comment:
  vim_org_id: 6066
  file_type: vim
  plugin_type: colors
  dir: candycode



- names: [blackboard.vim]
  authors: [Ben Wyrosdick]
  urls:
    - http://www.vim.org/scripts/script.php?script_id=2280
  description: 'Clone of the Blackboard theme from textmate '
  comment:
  vim_org_id: 11225
  file_type: vim
  plugin_type: colors
  dir: blackboard
